apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
      - name: dind
        image: docker:18.05-dind
        securityContext:
          privileged: true
        ports:
        - containerPort: 22
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}