---
name: Test Terraform Infrastructure
on: [push, pull_request]

jobs:
  build:
    name: Test Terraform Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

        # ~/go/pkg/mod
        # ~/go/src
          # /home/runner/work/flugel.it-test/flugel.it-test/go/pkg/mod
          # /home/runner/work/flugel.it-test/flugel.it-test/go/src
      - uses: actions/cache@v2
        with:
         path: |
            ~/go/pkg/mod
            ~/go/src
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
     
      # - name: link go modules in host to docker volume to have super linter grab the modules
      #   run: echo "::ln -s /home/runner /home/runner/work/_temp/_github_home"
      #   run: ln -s /home/runner /home/runner/work/_temp/_github_home
      
      - name: restore modules and print list of packages
        run: cd tests && go get -v && ls -Rl ~
        #run: cd tests && go get -v && cp -R ~/go /home/runner/work/flugel.it-test/flugel.it-test/go && ls -Rl ~
        # env:
        #   GOPATH: /home/runner/work/flugel.it-test/flugel.it-test/go
      # - name: copy modules and print list of packages
      #   run: cd tests && go get -v && ls -Rl ~

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

      # - name: Run Super-Linter
      #   uses: github/super-linter@v3
      #   env:
      #      DEFAULT_BRANCH: main
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #      VALIDATE_GO: true
      #      VALIDATE_TERRAFORM: true
      #      VALIDATE_TERRAFORM_TERRASCAN: true
      #      GOROOT: ""
          #  GOPATH: /github/workspace/go
      
      # - name: Run Super-Linter Manually not from docker
      #   env:
      #      DEFAULT_BRANCH: main
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #      VALIDATE_GO: true
      #      VALIDATE_TERRAFORM: true
      #      VALIDATE_TERRAFORM_TERRASCAN: true
      #      GOROOT: ""
      #   run: /home/runner/work/_actions/github/super-linter/v3/lib/linter.sh

      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_SKEY }}
        run: cd tests && go test -v -count=1