name: Test Terraform Infrastructure

on: [push, pull_request]

jobs:
  build:
    name: Test Terraform Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Run Super-Linter
      #   uses: github/super-linter@v3
      #   env:
      #      DEFAULT_BRANCH: testing
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v2
        with:
         path: ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         
      - name: restore modules
        run: cd tests && go get -v
      
      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_SKEY }}
          # TEST_AKEY: ${{ secrets.TEST_AKEY }}
          # TEST_SKEY: ${{ secrets.TEST_SKEY }}
        # run: |
        #   export AWS_ACCESS_KEY_ID="$TEST_AKEY"
        #   export AWS_SECRET_ACCESS_KEY="$TEST_SKEY"
        #   cd tests && go test -v -count=1
        run: cd tests && go test -v -count=1

