name: Test Terraform Infrastructure

on: [push, pull_request]

jobs:
  build:
    name: Test Terraform Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v2

      - name: execute tests
        run: go version
      # # Runs the Super-Linter action
      # - name: Run Super-Linter
      #   uses: github/super-linter@v3
      #   env:
      #     DEFAULT_BRANCH: testing
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}