---
name: Test Terraform Infrastructure
on: [push, pull_request]

jobs:
  build:
    name: Test Terraform Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
         path: ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         
      - name: restore modules
        run: cd tests && go get -v
      
      - name: Run Custom-Lintern
        runs:
          using: 'docker'
          image: './customLintern/Dockerfile'
          args:
            - ${{ inputs.who-to-greet }}
      
      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_SKEY }}
        run: cd tests && go test -v -count=1