---
name: Test Terraform Infrastructure
on: [push, pull_request]

jobs:
  build:
    name: Test Terraform Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
         path: |
            ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      
      - name: Restore modules and copy them to the volume mount path for Super-Linter
        run: |
          cd tests
          go get -v

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.29
          working-directory: ./tests
          args:  --timeout 10m
        env:
          GOROOT: ""
          GO111MODULE: "on"

      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_SKEY }}
        run: cd tests && go test -v -count=1 --timeout 30m